### ISSUE TITLE
visualization  issue

### ISSUE THREAD

**Issue by Phqqq** [facebookresearch/VideoPose3D#191]
Greetings，
      I've trained the model, and it won't load when visualization 
Traceback (most recent call last):
  File "run.py", line 221, in <module>
    model_traj.load_state_dict(checkpoint['model_traj'])
  File "F:\anaconda\anaconda1\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1196, in load_state_dict

**Comment by isaiah-li** [comment]
same error, anyone know about this?
