### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by Phqqq** [facebookresearch/VideoPose3D#192]
when i intend to  generate a visualization for humaneval

    Last message repeated 1 times
frame= 1045 fps=291 q=-0.0 Lsize=  940500kB time=00:00:17.48 bitrate=440765.2kbits/s speed=4.87x
video:940500kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
F:\VideoPose3D-master\common\visualization.py:198: UserWarning: Tight layout not applied. The left and right margins can
not be made large enough to accommodate all axes decorations.
  fig.tight_layout()
Traceback (most recent call last):
  File "F:\anaconda\anaconda1\envs\pt\lib\site-packages\matplotlib\animation.py", line 251, in saving
    yield self
  File "F:\anaconda\anaconda1\envs\pt\lib\site-packages\matplotlib\animation.py", line 1144, in save
    anim._init_draw()  # Clear the initial frame
  File "F:\anaconda\anaconda1\envs\pt\lib\site-packages\matplotlib\animation.py", line 1719, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
StopIteration

During handling of the above exception, another exception occurred:

**Comment by Kismetzc** [comment]
The same problem. Do you solve it?

**Comment by Kismetzc** [comment]
This has no effect on the result. I commented it out.
