### ISSUE TITLE
Test in the wild

### ISSUE THREAD

**Issue by chuhang** [facebookresearch/VideoPose3D#2]
Thanks for open-sourcing the code. Are you planning to release code for testing on an arbitrary input video, like the on shown in your "demo in the wild"?

**Comment by dariopavllo** [comment]
Hi,

Since the process is a bit involved, we did this manually. We might release automated code at some point, although we don't have a precise timeline.

I can give you some pointers on how to do it, but you'll have to write some code:

- First, you have to predicts the 2D keypoints from the video. You can use Detectron and the pretrained model on COCO (this is what we used). From an implementation perspective, you can either convert the video to a list of images (e.g. using ffmpeg) and run Detectron on the directory, or write custom code to run Detectorn on videos directly.

- For each frame, Detectron will emit a set of bounding boxes and the corresponding keypoints. If you assume that in your video there is only one person, you can just take the bounding box with the highest probability, otherwise you need to link people between frames (e.g. by bipartite matching on the bounding box overlap). We sticked with the simple single-person scenario.

- The next step is to predict the 2D keypoints using CPN, which requires the bounding boxes to be supplied externally. This is why we run Detectron first. CPN will give you slightly better poses, but you don't actually need to perform this step since it requires significant hacking of the CPN code. Detectron poses are already good enough.

- Finally, you have to create a "fake" dataset (a NumPy archive with the same tree structure as the ones we provided for Human3.6M or HumanEva) and run our code using a model trained on COCO poses from Detectron. We haven't yet released this pretrained model to the public, but we're going to do it in a few days (so stay tuned).

Let me know if you need more help!

**Comment by Dene33** [comment]
Really cool results, guys. Testing on an arbitrary input video/images is a must have for such a smooth implementation. :) Hope to see it soon!

**Comment by dariopavllo** [comment]
You can download the pretrained model here:
https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin

And the corresponding 2D detections are here (just for completeness -- you don't really need them to generate demos in the wild):
https://s3.amazonaws.com/video-pose-3d/data_2d_h36m_detectron_pt_coco.npz

Specifically, this one (currently unlisted in the documentation) is trained on the poses generated by the pretrained Detectron model. On Detectron, you have to use the configuration [12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml](https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml).

An important detail of this model is that it takes 3 coefficients per joint (instead of two), namely x, y, and the probability score from the heatmap. If you export the output tensors from Detectron, you will notice that there are 4 coefficients per joint (x, y, logit score before softmax, probability score after softmax), so you just need to take the indices 0, 1, and 3. You don't need to change anything in our code, since it already supports this kind of format.

**Comment by dariopavllo** [comment]
The format of our datasets is straightforward, e.g.

```python
data = np.load('data_2d_h36m_cpn_ft_h36m_dbb.npz')
actions = data['positions_2d'].item()
print(actions['S1']['Walking 1'][0].shape) # (3477, 17, 2)
```
The first index corresponds to the subject, the second to the action, and the third to the camera index.

**Comment by Dene33** [comment]
So, summarizing:
1. Convert desired video to images and process all the images by Detectron (with config provided);
2. Pack all the Detectron estimations into the `.npz` file, for example `our_detectron_2d_poses.npz`;
3. Adjust the code to define our `.npz` file:
`data = np.load('our_detectron_2d_poses.npz')`

So at the end we'll have command for visualizing like this (with adjusted model and path_to_video):
 `python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate` **d-pt-243.bin**  `--render --viz-subject S1 --viz-action Walking --viz-camera 0 --viz-video` **path_to_video** `--viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60`

Everything's right or I miss something?

P.S. Where do the names of actions come from (Detectron names actions, right?)? Where can I get full list and more information maybe? How should I define `--viz-action` at the end (how can I know how Detectron named the action)? Thank you!

**Comment by dariopavllo** [comment]
Yes, you got the general idea. Regarding points 2 and 3, the easiest (but hacky) solution would be to just modify our dataset (e.g. data_2d_h36m_detectron_pt_coco.npz) and replace one random action (e.g. Walking of subject S1) with the points provided by Detectron, but you are free to create a new one from scratch. You don't have to modify our code anyway. If you create a new one, make sure to specify it with the `-k` argument.

The action names are the original ones from Human3.6M, but they are arbitrary. You can name them as you wish.

**Comment by bucktoothsir** [comment]
so the only difference between https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin and https://s3.amazonaws.com/video-pose-3d/pretrained_h36m_cpn.bin is the way to get 2d joints?

**Comment by dariopavllo** [comment]
The difference is that one is trained on 2D poses from Detectron (pre-trained on COCO) and the other is trained on 2D poses from CPN (fine-tuned on Human3.6M). The architecture of the model is the same, the input on which it is trained is the only thing that changes.

**Comment by Dene33** [comment]
I've managed to run Detectron in Google Colab. You can check the notebook [here](https://github.com/Dene33/Detectron/blob/master/notebooks/detectron(google_colab).ipynb). As you can see Detectron returns `.jpg` or `.pdf` as output (didn't check other formats). So what format exactly do we need to have at the end to pack all of the output files to `.npz`? Is there some kinda argument in Detectron of should we adjust the code to extract bounding boxes and 2d joint?

I plan to create the `.ipynb` notebook for VideoPose3D to run in Google Colab as well, so help here is really appreciated. Thank you!

**Comment by Godatplay** [comment]
@Dene33 FYI your Download Files cell is not working. First it's missing a tuple, it should be:
`  if file.endswith(('.jpg', '.pdf')):`
Second, once that is fixed, there's a file not found error because the files are output with .jpg.jpg for some reason.

**Comment by Godatplay** [comment]
I'm trying to follow all the helpful instruction here, but I must admit I'm struggling and I apologize, I'm a beginner with Python and have no experience with Detectron before now. You mention we need to "run Detectron on the directory" and as mentioned above, infer_simple.py is simply for visualizing inference. Otherwise we could use test_net.py, which performs inference via test_engine's test_net, however it uses the configuration file to determine which image folder to run inference on. The config file listed above wants to process coco_2014_minival images. It also specifies a pre-set output directory, and outputs a Pickle file rather than a numpy archive. I tried searching the entire repo for numpy's savez but nothing came up.

Forgive my ignorance, but it seems like, at minimum, we'll have to write our own custom code for generating a numpy archive. This is fine, I'd just like to confirm this since I was unable to find any existing code relating to saving one out. I'm not missing something obvious, am I?

Assuming we need to write our own npz export code, do we also need to convert from cls format if we're using code based on infer_simple?

**Comment by Godatplay** [comment]
There's one specific area where I'm slightly confused. It seems like infer_simple.py only visualizes inference, it doesn't emit any other data, correct? test_net.py could be another option, but it takes its input folder from the config file. The config file you suggested we use wants to pull images from coco_2014_minival.

Did you mean use test_net.py and start with the config file but customize it as needed? Or is there some other process we should use that I'm missing?

**Comment by Godatplay** [comment]
Ah, reading the code more it looks like the list I had to wrap everything around is for the cameras. And for reference, the original data set:
`>>> actions['S1']['Walking 1'][0].shape[0]`
`3477`
my replacement:
`>>> myactions['S1']['Walking 1'][0].shape[0]`
`320`

**Comment by Godatplay** [comment]
I've been (clumsily heh) trying to debug my issue, and I _am_ running into a weird problem that may be related to the AssertionError, I can't tell yet. Whenever I try to save my camera list - i.e. the keypoints numpy array simply wrapping in a list as the only item - that list gets converted as another dimension in the enclosed numpy array. In other words my `[(320, 17, 4)]` turns into `(1, 320, 17, 4)`. And I have yet to find a way, with code at least, to prevent that my happening and just save a list to the archive.

In my reply above it shows the expected shape only because I used the Interpreter to manually build my data and replace the existing action. For some reason it worked in the Interpreter, but not in code? Here's my latest code attempt:
``` python
    list_with_camera = list()
    list_with_camera.append(keypoint_array) #keypoint_array is an ndarray of (320, 17, 4)
    dict = {'positions_2d': list_with_camera}
    np.savez("detections.npz", **dict)
    # results in (1, 320, 17, 4)
```

**Comment by Dene33** [comment]
You can reshape ndarray of shape (1, 320, 17, 4) to shape of (320, 17, 4) with `yourndarray.reshape(320, 17, 4)`

**Comment by Godatplay** [comment]
Ok, I figured it out, whew. I misinterpreted the comment above about coefficients per joint to mean that having 4 would be fine. It's not fine, there can only be 3.

If you're just replacing an action in the existing dataset with another one of a different length, you _do_ have to edit run.py to make sure ground truth is ignored.

**Comment by bucktoothsir** [comment]
> Ha! So unfortunately this is not working in my test example. Throughout time, the poses bounce around the image. Detectron results look great for this frame, though, with "person 1.00" detected. Are the 3d positions of the action I replaced influencing the inference?

what do you mean by 'the poses bounce around the image'?

**Comment by Godatplay** [comment]
![videopose3d-test](https://user-images.githubusercontent.com/198019/49892808-7bd01880-fe0f-11e8-86c9-c6fcecc6f3a5.gif)
Great question, apologies that it wasn't more clear. Here's a gif of me scrubbing along the timeline

**Comment by Godatplay** [comment]
Ok I think my issue was that I was constructing the archive basically from scratch, instead of using the provided tools. So I've started over with hopefully a better pipeline:

1. For each file inferred in Detectron, I add the keypoints and boxes to lists like so:
```
keypoints.append(cls_keyps)
boxes.append(cls_boxes)
```
2. I save those out like so:
```
np.savez_compressed(os.path.join(args.output_dir, "detections.npz"), boxes=boxes, keypoints=keypoints)
```
3. I rename the detections file to `Walking.54138969.mp4.npz` and place it in an S2 folder in my VideoPose3D data folder.
4. I run `python prepare_data_2d_h36m_generic.py -i . -o detectron_pt_coco_test` which searches for preprocessed h36m npzs and finds the one I just placed.
5. Looking at the resulting file `data_2d_h36m_detectron_pt_coco_test.npz` it seems to be missing the coefficients:
```
array({'S2': {'Walking': [array([], shape=(70, 17, 0), dtype=float32), None, None, None]}},
      dtype=object)
```
6. If I ignore that and try to run I get an AssertionError:
```
AssertionError: Subject S1 is missing from the 2D detections dataset
```
And if I comment out lines 67-81 in run.py, another:
```
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    kps[..., :2] = normalize_screen_coordinates(kps[..., :2], w=cam['res_w'], h=cam['res_h'])
  File "D:\VideoPose3D\common\camera.py", line 15, in normalize_screen_coordinates
    assert X.shape[-1] == 2
AssertionError
```
Any ideas on why the coefficients would get removed?

**Comment by dariopavllo** [comment]
As I said [here](https://github.com/facebookresearch/VideoPose3D/issues/2#issuecomment-444687031), Detectron exports 4 features per joint (x, y, logit score before softmax, probability score after softmax). You need to select the indices 0, 1, and 3, so that you end up with tensor of shape (17, 3).

I also think you missed a step. cls_boxes and cls_keyps contain all region proposals, including those that are not thresholded (this means that some of them may be wrong). This explains why your 2D pose is jumping across frames. Assuming that you have only one subject in your video, you should take the bounding box with the highest probability.

See this [sample implementation](https://github.com/facebookresearch/VideoPose3D/blob/cf94b42e1edf144f8eff2da0f43be737225e43bd/data/data_utils.py#L64-L81) (uncomment the last line and comment the other return statement).

**Comment by Godatplay** [comment]
Sorry if it wasn't clear, but before I streamlined everything, I was building my array more manually and it gave me a shape (n, 17, 3) where n was number of frames/images. My gif above was based on that result. I must have had some kind of problem constructing my data, though.

But then I saw your sample implementation and switched to that. Thanks for the suggestion! I didn't make the connection; switching that line definitely fixes my issue with not having data.

Now when I run, I get a TypeError:
```
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    kps[..., :2] = normalize_screen_coordinates(kps[..., :2], w=cam['res_w'], h=cam['res_h'])
TypeError: 'NoneType' object is not subscriptable
```
Here's some of my data:
``` python
>>> action['S2']['Walking'][0]
array([[[6.8634247e+02, 9.8111534e+01, 2.0278743e-02],
        [7.0029846e+02, 8.5118546e+01, 2.6080403e-02],
        [6.7438019e+02, 8.5118546e+01, 2.9254805e-02],
        ...,
        [5.7569147e+02, 4.5391971e+02, 7.8206295e-03],
        [6.9830475e+02, 5.5986261e+02, 6.7530833e-03],
        [6.2054999e+02, 5.5786365e+02, 4.9950532e-03]],

       [[6.6507806e+02, 1.0600409e+02, 1.7585000e-02],
        [6.8007416e+02, 9.3016640e+01, 2.4172412e-02],
        [6.5508069e+02, 9.2017609e+01, 2.5068793e-02],
        ...,
```

**Comment by Godatplay** [comment]
Using the built-in tools, unfortunately the output looks the same as when I built the numpy archive myself. As was suggested above, I've swapped commenting out lines 80 and 81 in `import_detectron_poses` in data_utils.py. Just to be sure, I also built my own 3d dataset with an action that has the same shape as my 2d action (except with 32 joints so it's gets reduced back down).

Just to be extra sure, before I run `prepare_data_2d_h36m_generic` which processes my data, I also pick the highest probability box in my infer file first. Here's the meat of my infer code for building the 2D and 3D data, which you can see is heavily based on `infer_simple`:
``` python
    keypoints = []
    boxes = []
    
    for i, im_name in enumerate(im_list):
        out_name = os.path.join(
            args.output_dir, '{}'.format(os.path.splitext(os.path.basename(im_name))[0] + '.' + args.output_ext)
        )
        logger.info('Processing {} -> {}'.format(im_name, out_name))
        im = cv2.imread(im_name)
        timers = defaultdict(Timer)
        t = time.time()
        with c2_utils.NamedCudaScope(0):
            cls_boxes, cls_segms, cls_keyps = infer_engine.im_detect_all(
                model, im, None, timers=timers
            )
        
        best_match = np.argmax(cls_boxes[1][:, 4])
        inferred_boxes = []
        inferred_boxes.append(cls_boxes[1][best_match])
        box_list = [[], np.array(inferred_boxes)]
        
        inferred_keypt_sets = []
        inferred_keypt_sets.append(np.array(cls_keyps[1][best_match]))
        keypt_set_list = [[], inferred_keypt_sets]
       
        keypoints.append(keypt_set_list)
        boxes.append(box_list)
    
    np.savez_compressed(os.path.join(args.output_dir, "Walking.54138969.mp4.npz"), boxes=boxes, keypoints=keypoints)
    
    output = {}
    output['S1'] = {}
    positions = []
    
    for i in range(len(keypoints)):
        pts = keypoints[i][1][0]
        pts = np.transpose(pts)
        pts = np.delete(pts, 3, 1)
        pts = np.append(pts, np.zeros((15, 3)), axis=0)
        positions.append(pts)
        
    positions = np.array(positions)
    output['S1']['Walking'] = positions.astype('float32')
    
    np.savez_compressed(os.path.join(args.output_dir, "data_3d_h36m.npz"), positions_3d=output)
```
Currently I'm assuming that the actual content of my 3D data is not important, I just started writing it this way trying to preserve formatting at first but in the end I'm guessing I could have just filled a whole ndarray of zeros.

**Comment by bucktoothsir** [comment]
> Currently I'm assuming that the actual content of my 3D data is not important, I just started writing it this way trying to preserve formatting at first but in the end I'm guessing I could have just filled a whole ndarray of zeros.

"Currently I'm assuming that the actual content of my 3D data is not important, I just started writing it this way trying to preserve formatting at first but in the end I'm guessing I could have just filled a whole ndarray of zeros." Your thought is right, cuz you don't have ground-truth and you don't need to vis it.

**Comment by Godatplay** [comment]
Thank you, yeah that was my assumption, but I guess I got superstitious once I got errors when the 3D data didn't match the 2D. Making my own 3D data (like you mentioned in the other issue) means I have to change less code. But as I've gotten to know the codebase more, it seems like the errors just come down to a lack of separation of concerns like I initially hoped.

**Comment by laowangFish** [comment]
> ![videopose3d_archive_org_vid_test](https://user-images.githubusercontent.com/198019/49886842-5851a180-fe00-11e8-8a38-5affba26f535.jpg)
> Ha! So unfortunately this is not working in my test example. Throughout time, the poses bounce around the image. Detectron results look great for this frame, though, with "person 1.00" detected. Are the 3d positions of the action I replaced influencing the inference?

**Comment by laowangFish** [comment]
the detectron's keypoints are not corresponding to the predicted 3D keypoints( no eyes, no ears), the upper figure make me confused, so the network change the keypints representation

**Comment by abhikhanna30** [comment]
> so the only difference between https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin and https://s3.amazonaws.com/video-pose-3d/pretrained_h36m_cpn.bin is the way to get 2d joints?



> so the only difference between https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin and https://s3.amazonaws.com/video-pose-3d/pretrained_h36m_cpn.bin is the way to get 2d joints?

Hi I dont get the difference between these two models? Can you explain.

**Comment by Godatplay** [comment]
Thanks for sharing this. Interesting, it looks like the ground truth's root motion is being used in the reconstruction. That would definitely mess up the projection to 3D.

**Comment by laowangFish** [comment]
> Thanks for sharing this. Interesting, it looks like the ground truth's root motion is being used in the reconstruction. That would definitely mess up the projection to 3D.

Thanks, I fixed my problem, it was the 2d keypoints data problem.

**Comment by Godatplay** [comment]
I *finally* got in-the-wild inference working with a quality that resembles the posted results. I used [AlphaPose with PoseFlow](https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/PoseFlow) to generate COCO-style keypoints, then I used the `cpn-pt-243.bin` model [mentioned here](https://github.com/facebookresearch/VideoPose3D/issues/12#issuecomment-449660973) along with a custom script I wrote to translate keypoints from a PoseFlow-tracked person to VideoPose3D format. My corresponding 3D npz is just ones in the proper shape.

Over the last couple days, I've had a lot of problems trying to visualize the results properly. The major issue has been that, regardless of skipping and frame limits, the entire input video is loaded into memory in raw format, which quickly runs out of RAM for any reasonable length video. I tried to customize that with ffmpeg options and other techniques, but just couldn't get it working. I gave up and just edited my input video to a smaller clip. The remaining issues are improper joint link indexing and the timing of the output is not synced up with the visualization timing. But the reconstruction looks quite similar to the posted results, with good prediction for the smoother movements and an averaging out of "sharper" movements, presumably due to such a high temporal window? Anyway, this is what I end up with:
![output](https://user-images.githubusercontent.com/198019/50567614-9d386c00-0d0c-11e9-8d43-c61c387487cc.gif)

**Comment by abhikhanna30** [comment]
@Godatplay hey your results look good. Even i am using the cpn_pt model. i just wanted to know that you our output 2d keypoints (COCO keypoints)  in which original dataset do you put it in. What i do id , i load data_2d_h36m_gt.npz and replace action Walking and subject S1 data with my N,17,2 coco keypoints. is that the correct approach?

**Comment by Godatplay** [comment]
One of these days I'll make a fork with my setup...until then I can say that I'm saving the npz I converted from COCO-style keypoints as `Walking.54138969.mp4.npz` in the $ROOT/data/S1 folder. This is because I'm using the included `prepare_data_2d_h36m_generic.py` to convert my file, and it'll crawl the data folder looking for subject folders and within them npz files with the structure `[action].[cam_id].mp4.npz`. Note I've changed that file such that the center and width and height match my video, and have removed the other camera entries from the cam_map list. My -o parameter is `cpn_pt_coco_test` so that the resulting file is `data_2d_h36m_cpn_pt_coco_test.npz` because I intentionally wanted to include `cpn` and `coco` in the name. That ndarray then only has the Walking action for only the S1 subject.

Since I've created the output you're referring to, I've switched to deepmatch-based PoseFlow instead of orb-based, which is supposed to be higher quality. But the results are jumbled up temporally. The pose of the first frame starts out correctly, but then it switches to posing the legs based on a different time of the clip, while the arms are referencing yet another time in the clip. Haven't had a chance to look into it yet, but it's certainly odd. I'm using a different part in this clip, so I'm not sure if that's related or not.

**Comment by lxy5513** [comment]
How to get keypts and bboxes ?

for 12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml. 
Is there any already traind model to get 2D keyps and bboxes? 
like this ` /path/to/e2e_keypoint_rcnn_R-101-FPN_s1x.kpl `

or I need to train on Detetron to get the model?Anyone can help me? thanks a lot

**Comment by lxy5513** [comment]
Is this `https://dl.fbaipublicfiles.com/detectron/37732318/12_2017_baselines/e2e_keypoint_rcnn_X-101-32x8d-FPN_s1x.yaml.16_55_09.Lx8H5JVu/output/train/keypoints_coco_2014_train%3Akeypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl` ?

**Comment by bucktoothsir** [comment]
@

> I made a fork with my version of the code that runs on in-the-wild/ your own video. [Here](https://github.com/tobiascz/VideoPose3D) is a link to my fork. Best to follow the Readme part I wrote but it is in an early stage so if you have any problems or remarks feel free to share!
> 
> I fixed the visualization problem of the 2D poses seen in the [output](https://github.com/facebookresearch/VideoPose3D/issues/2#issuecomment-450690343) created by @Godatplay .
> 
> I used the same in the wild video of the ice skating girl but my results are slightly worse than the one from the authors.
> 
> ### My output
> ![myOutput](https://github.com/tobiascz/VideoPose3D/blob/master/images/scater_girl.gif?raw=true)
> 
> ### Authors output
> ![authorsOutput](https://github.com/facebookresearch/VideoPose3D/blob/master/images/demo_yt.gif?raw=true)
> 
> I am not sure why my results are worse... If you have any idea let me know

hi you could check my issues. I came out the same problem and I figured it out.
https://github.com/facebookresearch/VideoPose3D/issues/6
https://github.com/facebookresearch/VideoPose3D/issues/23

**Comment by lxy5513** [comment]
@tobiascz 
your 2D keypoints accuracy is bad, Maybe you can try `AlphaPose` or `simple baselines of human pose estimation` to generate 2D keypoints , then feed them to the video pose.  

BTW, could you please give me the  origin ski video download adress ?

**Comment by tobiascz** [comment]
@lxy5513  [Video Link](https://www.youtube.com/watch?v=ke0iusvydl8)

Thanks for your comment I will continue this discussion in  Issue #6 !

**Comment by lxy5513** [comment]
@tobiascz, thanks. 
I integrate AlphaPose code to Video pose, [my videopose](https://github.com/lxy5513/videopose)   
Maybe you can reference it

**Comment by ihabkh** [comment]
> I _finally_ got in-the-wild inference working with a quality that resembles the posted results. I used [AlphaPose with PoseFlow](https://github.com/MVIG-SJTU/AlphaPose/tree/pytorch/PoseFlow) to generate COCO-style keypoints, then I used the `cpn-pt-243.bin` model [mentioned here](https://github.com/facebookresearch/VideoPose3D/issues/12#issuecomment-449660973) along with a custom script I wrote to translate keypoints from a PoseFlow-tracked person to VideoPose3D format. My corresponding 3D npz is just ones in the proper shape.
> 
> Over the last couple days, I've had a lot of problems trying to visualize the results properly. The major issue has been that, regardless of skipping and frame limits, the entire input video is loaded into memory in raw format, which quickly runs out of RAM for any reasonable length video. I tried to customize that with ffmpeg options and other techniques, but just couldn't get it working. I gave up and just edited my input video to a smaller clip. The remaining issues are improper joint link indexing and the timing of the output is not synced up with the visualization timing. But the reconstruction looks quite similar to the posted results, with good prediction for the smoother movements and an averaging out of "sharper" movements, presumably due to such a high temporal window? Anyway, this is what I end up with:
> ![output](https://user-images.githubusercontent.com/198019/50567614-9d386c00-0d0c-11e9-8d43-c61c387487cc.gif)

I'm using AlphaPose for 2D keypoints detection and PoseFlow for tracking. My idea is to visualize the 3D skeleton for the X tracked person using VidePose3D. I tried to build a script to convert the keypoints from PoseFlow into VideoPose3D format but it is not working well. Could you please advise. Thanks

**Comment by Alex-JYJ** [comment]
> As I said [here](https://github.com/facebookresearch/VideoPose3D/issues/2#issuecomment-444687031), Detectron exports 4 features per joint (x, y, logit score before softmax, probability score after softmax). You need to select the indices 0, 1, and 3, so that you end up with tensor of shape (17, 3).
> 
> I also think you missed a step. cls_boxes and cls_keyps contain all region proposals, including those that are not thresholded (this means that some of them may be wrong). This explains why your 2D pose is jumping across frames. Assuming that you have only one subject in your video, you should take the bounding box with the highest probability.
> 
> See this [sample implementation](https://github.com/facebookresearch/VideoPose3D/blob/cf94b42e1edf144f8eff2da0f43be737225e43bd/data/data_utils.py#L64-L81) (uncomment the last line and comment the other return statement).

I followed the suggestion to select the indices 0, 1, and 3, but the models in the line https://github.com/facebookresearch/VideoPose3D/blob/bc7db2c378cac881d324bc2b3d4b2b404b0dc619/run.py#L178 would accept the shape(17,2).  Can I just use the `kps[..., :2]`  to get it work?

**Comment by bobby20180331** [comment]
cool.
