### ISSUE TITLE
Visualization issues

### ISSUE THREAD

**Issue by SJayKim** [facebookresearch/VideoPose3D#205]
When I tried to visualize human3.6m video using pre-trained model, it raised the following error. I tried to solve it myself but failed to do so.

PS C:\Users\UNIST\desktop\Video_unist> python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin
--render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video "/path/to/videos/S11/Videos/Walking.54138969.mp4" --viz-outpu
t output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
>>
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024,
checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='h36m', dense=False, disable_optimizations=False, down
sample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_cpn.bin', export_training_curves=False, keypoints='cpn_ft_h36m_dbb', learni
ng_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9
,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='Walking', viz_bitrate=
3000, viz_camera=0, viz_downsample=2, viz_export=None, viz_limit=60, viz_no_ground_truth=False, viz_output='output.gif', viz_size=3, viz
_skip=0, viz_subject='S11', viz_video='/path/to/videos/S11/Videos/Walking.54138969.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Trainable parameter count: 16952371
Loading checkpoint checkpoint\pretrained_h36m_cpn.bin
This model was trained for 80 epochs
INFO: Testing on 225676 frames
Rendering...
Traceback (most recent call last):
  File "run.py", line 779, in <module>
    render_animation(input_keypoints, keypoints_metadata, anim_output,
  File "C:\Users\UNIST\desktop\Video_unist\common\visualization.py", line 112, in render_animation
    for f in read_video(input_video_path, skip=input_video_skip, limit=limit):
  File "C:\Users\UNIST\desktop\Video_unist\common\visualization.py", line 34, in read_video
    w, h = get_resolution(filename)
  File "C:\Users\UNIST\desktop\Video_unist\common\visualization.py", line 20, in get_resolution
    with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:
  File "C:\Users\UNIST\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\UNIST\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nies14** [comment]
@SunJunKimUnist could you please share the human3.6m videos with me?

**Comment by GiveMeFive-wgw** [comment]
I meet this problem too. Finally, it works by installing ffmpeg. I think your PC hasn't install ffmpeg @SunJunKimUnist

**Comment by suryateja0101** [comment]
How did you got the walking video?? Can you please share
