### ISSUE TITLE
Unable to execute run.py

### ISSUE THREAD

**Issue by gangubai** [facebookresearch/VideoPose3D#32]
**aki@Ak-Inspiron-3542:~/VideoPose3D-master$ python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video /home/ak/VideoPose3D-master/private/video/walk.mp4 --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60**
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='h36m', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_cpn.bin', export_training_curves=False, keypoints='cpn_ft_h36m_dbb', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='Walking', viz_bitrate=3000, viz_camera=0, viz_downsample=2, viz_limit=60, viz_no_ground_truth=False, viz_output='output.gif', viz_size=3, viz_skip=0, viz_subject='S11', viz_video='/home/ak/VideoPose3D-master/private/video/walk.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Trainable parameter count: 16952371
Loading checkpoint checkpoint/pretrained_h36m_cpn.bin
This model was trained for 80 epochs
INFO: Testing on 543344 frames
Rendering...
ffprobe: error while loading shared libraries: libx264.so.138: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "run.py", line 742, in <module>
    input_video_skip=args.viz_skip)
  File "/home/ak/VideoPose3D-master/common/visualization.py", line 100, in render_animation
    for f in read_video(input_video_path, skip=input_video_skip):
  File "/home/ak/VideoPose3D-master/common/visualization.py", line 26, in read_video
    w, h = get_resolution(filename)
TypeError: 'NoneType' object is not iterable

Can someone please tell me why I am getting this error.Please!!

**Comment by dariopavllo** [comment]
According to this line:
`ffprobe: error while loading shared libraries: libx264.so.138: cannot open shared object file: No such file or directory`
there is some problem with ffmpeg (it doesn't find the codec to decode mp4 videos). Make sure that it's installed correctly.

**Comment by gangubai** [comment]
How to execute the project for online video purpose,I mean live video from webcam to output ??
Previous issue was solved..
Thanks !!

**Comment by MuhammadAsadJaved** [comment]
Hi, 
     I am facing this problem while running run.py file. 

asad@asad-Z370P-D3:~/VideoPose3D$ python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video "images/danceHDN2.mp4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60

Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from generators import ChunkedGenerator, UnchunkedGenerator
  File "/home/asad/VideoPose3D/generators.py", line 8, in <module>
    from itertools import zip_longest
ImportError: cannot import name zip_longest

**Comment by MuhammadAsadJaved** [comment]
@dariopavllo  Yes I also realize this problem today. Thank you very much. But I was confused about something. Detectron is using Python 2.7,  This project is also working with Detectron, so how i can use both Python 2.7 and Python 3?

**Comment by dariopavllo** [comment]
If you use Anaconda, you can create multiple environments with different Python versions.
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by ericliwaseda** [comment]
D:\lqr\VideoPose3D-master>python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video "D:\lqr\VideoPose3D-master\data\h36m\h36m\S11\Video\backflat.MP4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='h36m', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_cpn.bin', export_training_curves=False, keypoints='cpn_ft_h36m_dbb', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='Walking', viz_bitrate=3000, viz_camera=0, viz_downsample=2, viz_limit=60, viz_no_ground_truth=False, viz_output='output.gif', viz_size=3, viz_skip=0, viz_subject='S11', viz_video='D:\\lqr\\VideoPose3D-master\\data\\h36m\\h36m\\S11\\Video\\backflat.MP4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Trainable parameter count: 16952371
Loading checkpoint checkpoint\pretrained_h36m_cpn.bin
This model was trained for 80 epochs
INFO: Testing on 543344 frames
Rendering...
Traceback (most recent call last):
  File "run.py", line 742, in <module>
    input_video_skip=args.viz_skip)
  File "D:\lqr\VideoPose3D-master\common\visualization.py", line 100, in render_animation
    for f in read_video(input_video_path, skip=input_video_skip):
  File "D:\lqr\VideoPose3D-master\common\visualization.py", line 26, in read_video
    w, h = get_resolution(filename)
  File "D:\lqr\VideoPose3D-master\common\visualization.py", line 20, in get_resolution
    with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。

Can someone please tell me why I am getting this error.Please!!

**Comment by jaykang1992** [comment]
> D:\lqr\VideoPose3D-master>python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video "D:\lqr\VideoPose3D-master\data\h36m\h36m\S11\Video\backflat.MP4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
> Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='h36m', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_cpn.bin', export_training_curves=False, keypoints='cpn_ft_h36m_dbb', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='Walking', viz_bitrate=3000, viz_camera=0, viz_downsample=2, viz_limit=60, viz_no_ground_truth=False, viz_output='output.gif', viz_size=3, viz_skip=0, viz_subject='S11', viz_video='D:\lqr\VideoPose3D-master\data\h36m\h36m\S11\Video\backflat.MP4', warmup=1)
> Loading dataset...
> Preparing data...
> Loading 2D detections...
> INFO: Receptive field: 243 frames
> INFO: Trainable parameter count: 16952371
> Loading checkpoint checkpoint\pretrained_h36m_cpn.bin
> This model was trained for 80 epochs
> INFO: Testing on 543344 frames
> Rendering...
> Traceback (most recent call last):
> File "run.py", line 742, in 
> input_video_skip=args.viz_skip)
> File "D:\lqr\VideoPose3D-master\common\visualization.py", line 100, in render_animation
> for f in read_video(input_video_path, skip=input_video_skip):
> File "D:\lqr\VideoPose3D-master\common\visualization.py", line 26, in read_video
> w, h = get_resolution(filename)
> File "D:\lqr\VideoPose3D-master\common\visualization.py", line 20, in get_resolution
> with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:
> File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 756, in **init**
> restore_signals, start_new_session)
> File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1155, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
> 
> Can someone please tell me why I am getting this error.Please!!

For those of you who stumbled upon this issue as I did. You only need to install ffmpeg as the author mentioned above. Download ffmpeg from https://ffmpeg.zeranoe.com/builds/ this link. make a directory in your C drive. add the bin folder to path. I spent quite some time to solve this issue, so I hope this reply reduce your time!

**Comment by wenwen12321** [comment]
Hi all, 

When I try to solve **FileNotFoundError: [Error 2] No such file or directory: ‘ffprobe’** problem.
I install ffmpeg from conda using following command:
```
$ conda config --add channels conda-forge
# conda install ffmpeg
```

But now I'm facing a new problem, error message as following:
```
ffprobe: symbol lookup error: /home/user/anaconda3/envs/pose/bin/../lib/./libgnutls.so.30: undefined symbol: mpn_add_1, version HOGWEED_4
Traceback (most recent call last):
  File "run.py", line 787, in <module>
    render_animation(input_keypoints, keypoints_metadata, anim_output,
  File "/home/user/papercode/VideoPose3D/common/visualization.py", line 118, in render_animation
    for f in read_video(input_video_path, skip=input_video_skip, limit=limit):
  File "/home/user/papercode/VideoPose3D/common/visualization.py", line 40, in read_video
    w, h = get_resolution(filename)
TypeError: cannot unpack non-iterable NoneType object
```

I have also try 
```
pip install ffmpeg
or
pip install ffprobe
or
conda install ffmpeg-python
```
they all don't work for me.
 
Can anyone point me out how to solve this issue?? 
Thanks in advance!!

**Comment by wenwen12321** [comment]
> Hi all,
> 
> When I try to solve **FileNotFoundError: [Error 2] No such file or directory: ‘ffprobe’** problem. I install ffmpeg from conda using following command:
> 
> ```
> $ conda config --add channels conda-forge
> # conda install ffmpeg
> ```
> 
> But now I'm facing a new problem, error message as following:
> 
> ```
> ffprobe: symbol lookup error: /home/user/anaconda3/envs/pose/bin/../lib/./libgnutls.so.30: undefined symbol: mpn_add_1, version HOGWEED_4
> Traceback (most recent call last):
>   File "run.py", line 787, in <module>
>     render_animation(input_keypoints, keypoints_metadata, anim_output,
>   File "/home/user/papercode/VideoPose3D/common/visualization.py", line 118, in render_animation
>     for f in read_video(input_video_path, skip=input_video_skip, limit=limit):
>   File "/home/user/papercode/VideoPose3D/common/visualization.py", line 40, in read_video
>     w, h = get_resolution(filename)
> TypeError: cannot unpack non-iterable NoneType object
> ```
> 
> I have also try
> 
> ```
> pip install ffmpeg
> or
> pip install ffprobe
> or
> conda install ffmpeg-python
> ```
> 
> they all don't work for me.
> 
> Can anyone point me out how to solve this issue?? Thanks in advance!!

I solve this problem from the following link:
https://stackoverflow.com/questions/75300900/conda-python-3-8-ffmpeg-ffprobe-symbol-lookup-error-anaconda3-envs-bin-lib/75301866#75301866

I hope it works for other who facing the same problem!!
