### ISSUE TITLE
Will you provide pretrained causal predict model?

### ISSUE THREAD

**Issue by zheLim** [facebookresearch/VideoPose3D#33]
Greetings!
I would like to know if you kindly can provide causal predict model ? Thanks in advance.

**Comment by dariopavllo** [comment]
Hi,

Sorry for the late answer!
You can download the pretrained model here:
https://dl.fbaipublicfiles.com/video-pose-3d/cpn-ft-243-dbb-causal.bin

Remember to use the flag `--causal` when testing it.

**Comment by luckymingjia** [comment]
Could this model be used for a wild video?what should i to do when using  causal predict model for a wild video? Could you tell me about it? Many thanks!!

**Comment by zheLim** [comment]
@dariopavllo Thanks a lot for your kindness!

**Comment by dariopavllo** [comment]
@zheLim You're welcome!

@luckymingjia You can use it out of the box, as if it were one of the other pretrained models. Just make sure to specify the flag `--causal`. In theory, if you accept a small delay, you can even do *almost* real-time prediction without the causal model. E.g. if you use the 27-frame model your predictions will be delayed by half (13 frames, that is, 0.26 seconds).

**Comment by hundanLi** [comment]
What is causal model?

**Comment by hundanLi** [comment]
I seems that it doesn't work well on custom videos. Please see this case: [case](https://drive.google.com/open?id=1JwSpFtq9tLEAuPBnP_62EqHwe9c2y6Da)

**Comment by neeek2303** [comment]
HI @dariopavllo ! Unfortunately, this model doesn't work. And moreover, there is an error with using this model. I tried to run ```python run.py -d custom -k ivan_demo -arc 3,3,3,3,3 -c checkpoint --evaluate cpn-ft-243-dbb-causal.bin --causal --render --viz-subject ivan_demo.mp4 --viz-action custom --viz-camera 0 --viz-video ./videos/ivan_demo.mp4 --viz-output output_video_causal.mp4 --viz-size 6 ```
and catch this error:
``` Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=True, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='cpn-ft-243-dbb-causal.bin', export_training_curves=False, keypoints='ivan_demo', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output_video_causal.mp4', viz_size=6, viz_skip=0, viz_subject='ivan_demo.mp4', viz_video='./videos/ivan_demo.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Using causal convolutions
INFO: Trainable parameter count: 16952371
Loading checkpoint checkpoint/cpn-ft-243-dbb-causal.bin
This model was trained for 80 epochs
Traceback (most recent call last):
  File "run.py", line 220, in <module>
    model_traj.load_state_dict(checkpoint['model_traj'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1018, in load_state_dict
    state_dict = state_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy' ```



Then I use ```if False:```  instead  ``` if args.evaluate and 'model_traj' in checkpoint: ``` on line 211. After that I was able to run code, but anyway I got terrible results

**Comment by scucszw** [comment]
> HI @dariopavllo ! Unfortunately, this model doesn't work. And moreover, there is an error with using this model. I tried to run `python run.py -d custom -k ivan_demo -arc 3,3,3,3,3 -c checkpoint --evaluate cpn-ft-243-dbb-causal.bin --causal --render --viz-subject ivan_demo.mp4 --viz-action custom --viz-camera 0 --viz-video ./videos/ivan_demo.mp4 --viz-output output_video_causal.mp4 --viz-size 6 `
> and catch this error:
> 
> ```
> Loading dataset...
> Preparing data...
> Loading 2D detections...
> INFO: Receptive field: 243 frames
> INFO: Using causal convolutions
> INFO: Trainable parameter count: 16952371
> Loading checkpoint checkpoint/cpn-ft-243-dbb-causal.bin
> This model was trained for 80 epochs
> Traceback (most recent call last):
>   File "run.py", line 220, in <module>
>     model_traj.load_state_dict(checkpoint['model_traj'])
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1018, in load_state_dict
>     state_dict = state_dict.copy()
> AttributeError: 'NoneType' object has no attribute 'copy' ```
> 
> 
> 
> Then I use ```if False:```  instead  ``` if args.evaluate and 'model_traj' in checkpoint: ``` on line 211. After that I was able to run code, but anyway I got terrible results 
> ```
Have you solved it?I get the same problem.
