### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wm901115nwpu** [facebookresearch/VideoPose3D#56]
When I run:
#!/bin/bash
~/anaconda3/bin/python run.py -d humaneva15 -k detectron_pt_coco -str Train/S1,Train/S2,Train/S3 -ste Validate/S1,Validate/S2,Validate/S3 -c checkpoint --evaluate pretrained_humaneva15_detectron.bin  --render --viz-subject Validate/S2 --viz-action "Walking 1 chunk0" --viz-camera 0 --viz-output output_he.gif --viz-size 3 --viz-downsample 2 --viz-video "/home/wangmeng/humaneva/S2/Image_Data/Walking_1_(C1).avi" --viz-skip 115 --viz-limit  100

assert keypoints[subject][action][cam_idx].shape[0] >= mocap_length

**Comment by dariopavllo** [comment]
Did you get any errors when converting the HumanEva dataset? Did you follow all steps carefully (including applying the update)?

**Comment by wm901115nwpu** [comment]
Rendering...
Traceback (most recent call last):
  File "run.py", line 742, in <module>
    input_video_skip=args.viz_skip)
TypeError: render_animation() missing 1 required positional argument: 'output'

**Comment by wm901115nwpu** [comment]
I don't apply the update.

**Comment by wm901115nwpu** [comment]
When I apply the update, I occured the problem:
Rendering...
Traceback (most recent call last):
File "run.py", line 742, in 
input_video_skip=args.viz_skip)
TypeError: render_animation() missing 1 required positional argument: 'output'

**Comment by wm901115nwpu** [comment]
I find visualization.py, the function is defined:
def render_animation(keypoints, keypoints_metadata, poses, skeleton, fps, bitrate, azim, output, viewport,
                     limit=-1, downsample=1, size=6, input_video_path=None, input_video_skip=0):

In the run.py, call the render_animation:

render_animation(input_keypoints, input_keypoints, anim_output,
                     dataset.skeleton(), dataset.fps(), args.viz_bitrate, cam['azimuth'], args.viz_output,
                     limit=args.viz_limit, downsample=args.viz_downsample, size=args.viz_size,
                     input_video_path=args.viz_video, viewport=(cam['res_w'], cam['res_h']),
                     input_video_skip=args.viz_skip)

it lack of keypoints_metadata.
