### ISSUE TITLE
inference own video

### ISSUE THREAD

**Issue by wm901115nwpu** [facebookresearch/VideoPose3D#62]
How to inference own video?

**Comment by Justinemmerich** [comment]
check out https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md

I have created a Google Colab Jupyter Notebook for this. 
You can get it here: [Google Colab Notebook - Facebook VideoPose3D Inference in the wild](https://github.com/Justinemmerich/VideoPose3D/blob/master/Notebook/Facebook_VideoPose3D_Inference_in_the_wild_Detectron.ipynb)

Go to - [https://colab.research.google.com/](https://colab.research.google.com/) 
click on Github Tab
add the ipynb link above

everything worked so far, detectron 2D joint detection ,but I have problems to generate the 3D joints 

> Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='MyCustomDatasetName', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
>
> 
> Loading dataset...
> Preparing data...
> Loading 2D detections...
> 
> Traceback (most recent call last):
>   File "run.py", line 169, in <module>
>     cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
>   File "run.py", line 115, in fetch
>     for action in keypoints[subject].keys():
> KeyError: 'video.mp4'

**Comment by Justinemmerich** [comment]
everything works now in Colab!

**Comment by gnool** [comment]
@Justinemmerich The notebook seems to be pointing at a broken link at anaconda's webpage.

**Comment by Justinemmerich** [comment]
@gnool thanks, I have noticed this but had no time to fix it (make a change request ). it broke a few times due to anaconda updates

**Comment by philno27** [comment]
> @gnool thanks, I have noticed this but had no time to fix it ~(make a change request )~. it broke a few times due to anaconda updates. I have updated the source!



> check out https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md
> 
> I have created a Google Colab Jupyter Notebook for this.
> You can get it here: [Google Colab Notebook - Facebook VideoPose3D Inference in the wild](https://github.com/Justinemmerich/VideoPose3D/blob/master/Notebook/Facebook_VideoPose3D_Inference_in_the_wild_Detectron.ipynb)
> 
> Go to - https://colab.research.google.com/
> click on Github Tab
> add the ipynb link above
> 
> everything worked so far, detectron 2D joint detection ,but I have problems to generate the 3D joints
> 
> > Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='MyCustomDatasetName', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
> > Loading dataset...
> > Preparing data...
> > Loading 2D detections...
> > Traceback (most recent call last):
> > File "run.py", line 169, in 
> > cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
> > File "run.py", line 115, in fetch
> > for action in keypoints[subject].keys():
> > KeyError: 'video.mp4'

hello.What is your problem resolved yet, I there have been problems just like you do

**Comment by Justinemmerich** [comment]
@philno27 I can not understand what your comment should mean. Is there a problem with the  colab Implementation ? I have checked the Code, it works as accepted!

**Comment by philno27** [comment]
thank you for your reply!!! I just follow this https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md and run zhe model on my video with the pycharm.It prompted me following error:
python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject output.mp4 --viz-action custom --viz-camera 0 --viz-video /path/to/output.mp4 --viz-output output.gif --viz-size 6
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.gif', viz_size=6, viz_skip=0, viz_subject='output.mp4', viz_video='/path/to/output.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
Traceback (most recent call last):
  File "run.py", line 169, in <module>
    cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
  File "run.py", line 115, in fetch
    for action in keypoints[subject].keys():
KeyError: 'output.mp4'

**Comment by philno27** [comment]
> @philno27 I can not understand what your comment should mean. Is there a problem with the colab Implementation ? I have checked the Code, it works as accepted!
thank you for your reply!!! I just follow this https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md and run zhe model on my video with the pycharm.It prompted me following error:
python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject output.mp4 --viz-action custom --viz-camera 0 --viz-video /path/to/output.mp4 --viz-output output.gif --viz-size 6
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.gif', viz_size=6, viz_skip=0, viz_subject='output.mp4', viz_video='/path/to/output.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
Traceback (most recent call last):
File "run.py", line 169, in 
cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
File "run.py", line 115, in fetch
for action in keypoints[subject].keys():
KeyError: 'output.mp4

**Comment by philno27** [comment]
> @philno27 I can not understand what your comment should mean. Is there a problem with the colab Implementation ? I have checked the Code, it works as accepted!

thank you for your reply!!! I just follow this https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md and run zhe model on my video with the pycharm.It prompted me following error:
python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject output.mp4 --viz-action custom --viz-camera 0 --viz-video /path/to/output.mp4 --viz-output output.gif --viz-size 6
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.gif', viz_size=6, viz_skip=0, viz_subject='output.mp4', viz_video='/path/to/output.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
Traceback (most recent call last):
File "run.py", line 169, in 
cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
File "run.py", line 115, in fetch
for action in keypoints[subject].keys():
KeyError: 'output.mp4

**Comment by wesonchen** [comment]
> > @philno27 I can not understand what your comment should mean. Is there a problem with the colab Implementation ? I have checked the Code, it works as accepted!
> 
> thank you for your reply!!! I just follow this https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md and run zhe model on my video with the pycharm.It prompted me following error:
> python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject output.mp4 --viz-action custom --viz-camera 0 --viz-video /path/to/output.mp4 --viz-output output.gif --viz-size 6
> Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.gif', viz_size=6, viz_skip=0, viz_subject='output.mp4', viz_video='/path/to/output.mp4', warmup=1)
> Loading dataset...
> Preparing data...
> Loading 2D detections...
> Traceback (most recent call last):
> File "run.py", line 169, in
> cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
> File "run.py", line 115, in fetch
> for action in keypoints[subject].keys():
> KeyError: 'output.mp4

Hello,Have you solved this problem？I have the same problem.

**Comment by SaugatBhattarai** [comment]
I have the same issue has anyone solved this?

**Comment by wesonchen** [comment]
@SaugatBhattarai  Check the `data_2d_custom_myvideos.npz`  you generate in step 4.   The `/path/to/detections/output_directory` in `python prepare_data_2d_custom.py -i /path/to/detections/output_directory -o myvideos` have to change to the path of `data_2d_custom_myvideos.npz` you generate in Step3. I solved the problem in this way. I hope this would help you.

**Comment by SaugatBhattarai** [comment]
@wesonchen  Thank you for point out the path issue. JUST ADDING SOMETHING OF MY CONTEXT. I have created output_directory in VideoPose3D root directory and I am running this code inside 'data' directory. 
**WRONG**: python3 prepare_data_2d_custom.py -i output_directory -o myvideos
**CORRECTED**: python3 prepare_data_2d_custom.py -i ../output_directory -o myvideos

**Comment by neeek2303** [comment]
@SaugatBhattarai it didn't work even after your suggestion :(

**Comment by harshap-ai** [comment]
> check out https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md
> 
> I have created a Google Colab Jupyter Notebook for this. You can get it here: [Google Colab Notebook - Facebook VideoPose3D Inference in the wild](https://github.com/Justinemmerich/VideoPose3D/blob/master/Notebook/Facebook_VideoPose3D_Inference_in_the_wild_Detectron.ipynb)
> 
> Go to - https://colab.research.google.com/ click on Github Tab add the ipynb link above
> 
> everything worked so far, detectron 2D joint detection ,but I have problems to generate the 3D joints
> 
> > Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='MyCustomDatasetName', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
> > Loading dataset...
> > Preparing data...
> > Loading 2D detections...
> > Traceback (most recent call last):
> > File "run.py", line 169, in 
> > cameras_valid, poses_valid, poses_valid_2d = fetch(subjects_test, action_filter)
> > File "run.py", line 115, in fetch
> > for action in keypoints[subject].keys():
> > KeyError: 'video.mp4'

I faced an error running the Caffe2 Installation as pytorch version 1.2.0 seems to be incompatible in Colab. Probably because of the Python version being 3.x
So I modified the torch installation to version 1.0.1: (and it worked!) 

!wget https://anaconda.org/pytorch/pytorch/1.0.1/download/linux-64/pytorch-1.0.1-py3.7_cuda10.0.130_cudnn7.4.2_2.tar.bz2
!tar xvjf pytorch-1.0.1-py3.7_cuda10.0.130_cudnn7.4.2_2.tar.bz2
!cp -r lib/python3.7/site-packages/* /usr/local/lib/python3.7/dist-packages/

Thank you for the wonderful book btw, @Justinemmerich

**Comment by TigerWzWings** [comment]
> 
Same Issue and I solved it. 
I think this KeyError was caused by path settings. In STEP3: Inferring 2D Keypoints with Detectron, "**__--output-dir output_directory_**_" is not clear."_**output_directory"**_should be claimed as absoluted path just like _**"~/ViedoPose3D/detecions/output_directory"**_., and this folder for output it's only one under "/**detections**". I was thought there's another one folder got same name under "**/inference**" but that was wrong, don't create the output_directory folder under **"/inference"** that's the point. 
Change the path to "**/detections**" and Code will be run correct.
Hope this will helps. It works for me :)
