### ISSUE TITLE
Matplotlib Error

### ISSUE THREAD

**Issue by Hwang-dae-won** [facebookresearch/VideoPose3D#74]
When I run run.py I get the following error: 

Traceback (most recent call last):
  File "run.py", line 760, in <module>
    input_video_skip=args.viz_skip)
  File "/home/dw/1.Code/VideoPose3D/common/visualization.py", line 91, in render_animation
    ax.set_aspect('equal')
  File "/home/dw/anaconda3/envs/pytorch3.6/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

Why does this happen?

If I delete "ax.set_aspect ('equal')" in ./common / visualization.py ", line 91 and run it, it will run properly.

**Comment by hundanLi** [comment]
Maybe need to use version 2.2 of matplotlib
