### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_3d_h36m.npz'

### ISSUE THREAD

**Issue by no-Seaweed** [facebookresearch/VideoPose3D#97]
Where do I download the following npz file from?

```
[shukaif@scc-c10 shukai]$ cd VideoPose3D/
[shukaif@scc-c10 VideoPose3D]$ mkdir checkpoint
[shukaif@scc-c10 VideoPose3D]$ cd checkpoint
[shukaif@scc-c10 checkpoint]$ wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_cpn.bin
--2019-11-06 20:22:35--  https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_cpn.bin
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.22.166, 104.20.6.166, 2606:4700:10::6814:6a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.22.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67889963 (65M) [application/octet-stream]
Saving to: 'pretrained_h36m_cpn.bin'

100%[=================================================================================================>] 67,889,963  20.0MB/s   in 3.6s   

2019-11-06 20:22:40 (18.0 MB/s) - 'pretrained_h36m_cpn.bin' saved [67889963/67889963]

[shukaif@scc-c10 checkpoint]$ wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_humaneva15_detectron.bin
--2019-11-06 20:22:41--  https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_humaneva15_detectron.bin
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.22.166, 104.20.6.166, 2606:4700:10::6814:6a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.22.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34242417 (33M) [application/octet-stream]
Saving to: 'pretrained_humaneva15_detectron.bin'

100%[=================================================================================================>] 34,242,417  15.5MB/s   in 2.1s   

2019-11-06 20:22:44 (15.5 MB/s) - 'pretrained_humaneva15_detectron.bin' saved [34242417/34242417]

[shukaif@scc-c10 checkpoint]$ cd ..
[shukaif@scc-c10 VideoPose3D]$ python run.py -k cpn_ft_h36m_dbb -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin
Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='h36m', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_cpn.bin', export_training_curves=False, keypoints='cpn_ft_h36m_dbb', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=False, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action=None, viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output=None, viz_size=5, viz_skip=0, viz_subject=None, viz_video=None, warmup=1)
Loading dataset...
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    dataset = Human36mDataset(dataset_path)
  File "/projectnb2/dnn-motion/shukai/VideoPose3D/common/h36m_dataset.py", line 234, in __init__
    data = np.load(path, allow_pickle=True)['positions_3d'].item()
  File "/share/pkg.7/python3/3.6.5/install/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_3d_h36m.npz'
```

**Comment by simonefelicioni** [comment]
Hi @no-Seaweed , I faced the same issue. Have you found a solution for that?

**Comment by hyaxzz** [comment]
I had the same problem

**Comment by hyaxzz** [comment]
I had the same problem

**Comment by dariopavllo** [comment]
The file is created by downloading the dataset and running the preprocessing scripts.
See https://github.com/facebookresearch/VideoPose3D/blob/master/DATASETS.md

**Comment by qingyuanchen1997** [comment]
I didn't get the data. Would you please send the zip to me, and this is my mailbox: qingyuanchen@stu.xjtu.edu.cn. Thanks very much!!! @dariopavllo

**Comment by qingyuanchen1997** [comment]
I didn't get the data. Would you please send the data_3d_h36m.npz to me? and this is my mailbox: qingyuanchen@stu.xjtu.edu.cn. Thanks very much!!!

**Comment by qingyuanchen1997** [comment]
I didn't get the data. Would you please send the data_3d_h36m.npz to me? and this is my mailbox: qingyuanchen@stu.xjtu.edu.cn. Thanks very much!!! @dariopavllo @hyaxzz @no-Seaweed

**Comment by ShinSeungChul** [comment]
I have same issue.....
Would you please send the data_3d_h36m.npz to me??????
my email: crazy_ssc@naver.com
please...
Thanks!!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997

**Comment by zarff** [comment]
I have the same error when I run my own code but the difference is that I have the dataset but I do not know where should I copy or upload the file? Could you please help me to solve that? 

The error is:
 File "/home/name/anaconda3/envs/project/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cifar_RGB_4bit.npz'

**Comment by 123guozhiyu** [comment]
I also  have same issue.....
Would you please send the data_3d_h36m.npz to me?
my email: 15847251795@163.com
help me !!!!!!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997

**Comment by Raneee** [comment]
I also have same issue.....
Would you please send the data_3d_h36m.npz to me?
my email: 374939266@qq.com
thanks!! @ShinSeungChul @dariopavllo @123guozhiyu @no-Seaweed @hyaxzz

**Comment by hsw1005** [comment]
Would you please send the data_3d_h36m.npz to me?

email : hsw_1005@naver.com
@ShinSeungChul  @dariopavllo  @123guozhiyu  @no-Seaweed  @hyaxzz

Thank you.

**Comment by shineway14** [comment]
...
Would you please send the data_3d_h36m.npz to me?

email : 408780518@qq.com
@ShinSeungChul @dariopavllo @123guozhiyu @no-Seaweed @hyaxzz @develop-hsw

**Comment by dungdo123** [comment]
Would you please send the data_3d_h36m.npz to me too?

Email : dungdo.hust@gmail.com

Thank you so much!
@ShinSeungChul @dariopavllo @123guozhiyu @no-Seaweed @hyaxzz @develop-hsw

**Comment by laomaup** [comment]
I also have same error, would you please send the data_3d_h36m.npz to me?
my email: majingqiauto123@126.com
thank you!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997

**Comment by zhongxiaoting** [comment]
I also have same error, would you please send the data_3d_h36m.npz to me?
my email: z1915270314@163.com
thank you!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo  @123guozhiyu  @laomaup

**Comment by RCpengnan** [comment]
I didn't get the data. Would you please send the data_3d_h36m.npz to me? and this is my mailbox: 2450856237@qq.com. Thanks very much!!! @dariopavllo @hyaxzz @no-Seaweed

**Comment by rohatgiy** [comment]
I couldn't get the file, could anyone please send me the data_3d_h36m.npz dataset?

Thank you so much!!

email: yrohatgi@uwaterloo.ca

@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by heduo-star** [comment]
I couldn't get the file, could anyone please send me the data_3d_h36m.npz dataset?

Thank you so much!!

email: 2969768979@qq.com

@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by kangel429** [comment]
I couldn't get the file, could anyone please send me the data_3d_h36m.npz dataset?

Thank you so much!

email: **limlim_e@naver.com**

@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by muhabdulhaq** [comment]
If anyone have the the data_2d_h36m_gt.npz and data_3d_h36m.npz file, can you please share to me,
haq-muhammad@ed.tmu.ac.jp

Thank you,

**Comment by tdat1995** [comment]
I couldn't find the data_2d_h36m_gt.npz and data_3d_h36m.npz file, Can you share it for me?
Thank you so so much!
email: ttd9x1995@gmail.com
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by thmteam2000** [comment]
No such file or directory: 'data/data_3d_h36m.npz'
I couldn't download the data_3D_h36m.npz
I'm waiting for the sign approval about a month....
email: thmteam2000@kau.kr

**Comment by GavinLU7** [comment]
I also have same error, would you please send the data_3d_h36m.npz to me?
my email: luxiyan@outlook.com
thank you!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by phan-kimngan** [comment]
I also have same error, would you please send the data_3d_h36m.npz to me?
my email: luxiyan@outlook.com
thank you!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by phan-kimngan** [comment]
I also have same error, would you please send the data_3d_h36m.npz to me?
my email: kimngan260997@gmail.com
thank you!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by DeepBlue4794** [comment]
I also have the same error, would you please send the data_3d_h36m.npz to me?
my email: antasid@gapp.nthu.edu.tw
Thank you!
@dariopavllo

**Comment by enes3774** [comment]
I also have the same error, would you please send the data_3d_h36m.npz to me?
my email: enesmahmut3774@gmail.com

**Comment by tobibaum** [comment]
has anyone had luck getting the data this way? if so, could you send me a link to the file as well?
tobibaum@gmail.com

thank you very much!!

**Comment by enes3774** [comment]
Nobody send me a file.I have to visit yhis website and login but i havent
got any education account.so i couldnt get data.
My email: enesmahmut3774@gmail.com

**Comment by buone2** [comment]
I also have the same error, would you please send the data_3d_h36m.npz to me?
my email : qbdbhs2365@gmail.com
Thank you very much!!!

**Comment by MShirshekar** [comment]
I also have same error, would you please send the data_3d_h36m.npz to me?
my email: [mohammadshirshekar@outlook.com](mailto:mohammadshirshekar@outlook.com)
thank you! 🤠🙏
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by dorattnc** [comment]
I also have the same error, would you please send the data_3d_h36m.npz to me? If anyone else has been able to receive the dataset this way, I would greatly appreciate it if you could send me the data!
my email : [tutuncudora@gmail.com](mailto:tutuncudora@gmail.com)
Thank you greatly!
@dariopavllo @hyaxzz @no-Seaweed @qingyuanchen1997 @ShinSeungChul @dariopavllo @123guozhiyu @laomaup

**Comment by cha-noong** [comment]
I also have the same error, would you please send the data_3d_h36m.npz to me?
my email : kcw4875@gmail.com
Thank you greatly!! :)

**Comment by mwaqas-sudo** [comment]
I also have the same error, would you please send the data_3d_h36m.npz to me?
my email : [waqasbilal02@gmail.com](mailto:waqasbilal02@gmail.com)
Thank you greatly!! :)
